// packages/micro-front-end/qiankun-test/child-vue/src/CardList.vue
<template>
  <div class="card-list">
    <Row :gutter="20">
      <Col
        v-for="(url, index) in images"
        :key="url"
        :span="6"
      >
        <Card
          hoverable
          style="width: 100%;"
          @click="onClick(index)"
        >
          <template #cover>
            <img alt="example" :src="url">
          </template>
          <CardMeta title="Card title" description="This is the description">
            <template #avatar>
              <Avatar :src="avatar" />
            </template>
          </CardMeta>
        </Card>
      </Col>
    </Row>
  </div>
</template>

<script setup lang="ts">
  import { useRouter } from 'vue-router'
  import { Card, Row, Col, CardMeta, Avatar } from 'ant-design-vue'
  import image1 from './assets/image1.png'
  import image2 from './assets/image2.png'
  import image3 from './assets/image3.png'
  import image4 from './assets/image4.png'
  import avatar from './assets/avatar1.png'

  const images = [
    image1,
    image2,
    image3,
    image4,
  ]

  const router = useRouter()
  function onClick(index: number) {
    router.push({
      name: 'CardDetail',
      params: { index },
    })
  }
</script>

// packages/micro-front-end/micro-app-test/child-react/src/CardList.tsx
import { useNavigate } from 'react-router'
import { Row, Col, Card, Avatar } from 'antd'
import image1 from './assets/image1.png'
import image2 from './assets/image2.png'
import image3 from './assets/image3.png'
import image4 from './assets/image4.png'
import avatar from './assets/avatar1.png'

const images = [
  image1,
  image2,
  image3,
  image4,
]

export default function CardList() {
  const navigate = useNavigate()

  function onClick(index: number) {
    navigate(`/detail/${index}`)
  }

  return (
    <Row gutter={20}>
      {images.map((url, index) => (
        <Col key={url} span={6}>
          <Card
            hoverable
            style={{ width: '100%' }}
            onClick={() => onClick(index)}
            cover={<img alt="example" src={url} />}
          >
            <Card.Meta
              title="React title"
              description="This is the description"
              avatar={<Avatar src={avatar} />}
            />
          </Card>
        </Col>
      ))}
    </Row>
  )
}
